name: Google Meet Final Join

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg xvfb fluxbox google-chrome-stable pulseaudio xdotool

      - name: Run Meet Stream
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MEET_URL: ${{ secrets.MEET_URL }}
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          pulseaudio --start --exit-idle-time=-1
          fluxbox &
          sleep 5

          # Chrome Launch (Fake Mic/Cam ke sath)
          google-chrome-stable --no-sandbox \
            --no-first-run \
            --disable-blink-features=AutomationControlled \
            --use-fake-ui-for-media-stream \
            --use-fake-device-for-media-stream \
            --start-maximized \
            "$MEET_URL" &

          sleep 50 # Page ko poora load hone do (Screnshot wali stage tak)

          # --- AUTO FILL NAME & JOIN ---
          
          # 1. 'What's your name' box select karne ke liye 1 baar Tab
          xdotool key Tab
          sleep 2
          
          # 2. Naam type karna
          xdotool type "FAIZ 1611 LIVE"
          sleep 2
          
          # 3. 'Join' button par pahunchne ke liye Enter
          xdotool key Return
          sleep 10 # Waiting for host to admit or auto-join

          # 4. Agar 'Ask to join' ke baad koi aur popup aaye
          xdotool key Escape
          sleep 2

          # --- FFmpeg YouTube Stream ---
          ffmpeg -f x11grab -video_size 1920x1080 -i :99.0 \
          -f pulse -i default -c:v libx264 -preset veryfast \
          -b:v 3000k -maxrate 3000k -bufsize 6000k \
          -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k \
          -f flv "rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY" &

          sleep 42600s

      - name: Restart Workflow
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/meet_stream.yml/dispatches \
          -d '{"ref":"main"}'
          
